action_selector: multinomial
agent_model: mackrl_recursive
agent_output_type: policies
agent_share_params: True
agent_level1_share_params: True
agent_level2_share_params: True
agent_level3_share_params: True
critic_share_params: True
lr_agent: 5e-4
lr_critic: 5e-4
mackrl_agent_model: mackrl_agent
mackrl_agent_model_level1: mackrl_recurrent_agent_level1
mackrl_agent_model_level2: mackrl_recurrent_agent_level2
mackrl_agent_model_level3: mackrl_recurrent_agent_level3
mackrl_agent_use_past_actions: True
mackrl_critic: mackrl_critic
mackrl_critic_use_past_actions: True
mackrl_critic_use_sampling: False
mackrl_critic_sample_size: 1000
mackrl_epsilon_start_level1: 0.5
mackrl_epsilon_finish_level1: 0.01
mackrl_epsilon_time_length_level1: 50000
mackrl_epsilon_decay_mode_level1: "exp"
mackrl_exploration_mode_level1: "softmax"
mackrl_epsilon_start_level2: 0.5
mackrl_epsilon_finish_level2: 0.01
mackrl_epsilon_time_length_level2: 50000
mackrl_epsilon_decay_mode_level2: "exp"
mackrl_exploration_mode_level2: "softmax"
mackrl_epsilon_start_level3: 0.5
mackrl_epsilon_finish_level3: 0.01
mackrl_epsilon_time_length_level3: 50000
mackrl_epsilon_decay_mode_level3: "exp"
mackrl_exploration_mode_level3: "softmax"
mackrl_use_entropy_regularizer: False
mackrl_use_obs_intersections: True
mackrl_entropy_loss_regularization_factor: 0.000005
mackrl_delegation_probability_bias: 0.0
mackrl_obs_intersection_noise: ~
gamma: 0.99
n_step_return_n: 1
n_pair_samples: 1
learner: mackrl
multiagent_controller: mackrl_mac
n_critic_learner_reps: 4
obs_last_action: True
runner: mackrl
T_target_critic_update_interval: 661500
td_lambda: 0.8
use_replay_buffer: False
mackrel_logit_bias: 1.5
use_batch_norm: True
use_full_observability: False
mackrl_fix_level1_pair: False
mackrl_delegate_if_zero_ck: True
mackrl_always_delegate: False
mackrl_logit_bias: 0.0
critic_use_past_actions: True
fix_partition_size: False
obs_noise: False
obs_noise_std: 0.1

